language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: SYMFONY_VERSION="2.8.*"
    - php: 5.6
      env: SYMFONY_VERSION="2.8.*" DEPENDENCIES=dev
    - php: 5.6
      env: SYMFONY_VERSION="3.0.*"
    - php: 5.6
      env: SYMFONY_VERSION="3.0.*" DEPENDENCIES=dev
    - php: 5.6
      env: DEPENDENCIES=dev
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.0
      env: SYMFONY_VERSION="2.8.*"
    - php: 7.0
      env: SYMFONY_VERSION="2.8.*" DEPENDENCIES=dev
    - php: 7.0
      env: SYMFONY_VERSION="3.0.*"
    - php: 7.0
      env: SYMFONY_VERSION="3.0.*" DEPENDENCIES=dev
    - php: 7.0
      env: DEPENDENCIES=dev
  allow_failures:
  - env: DEPENDENCIES=dev

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - phpunit -v --coverage-text

notifications:
  slack:
    secure: Pb1VbzHxsyJR330oaqdv5jpF4nlaNxlzSe2sxq2oNfj5J3NR4WZxjmLYiEeMEH4JSYocwePud+6GOVSiM08TjZ/+Ahgv0AkCzScXkTUtHTkW451A2Bewu4nR5O1Nl5hf+AKcV1p1rICfc4MWZIL3jSDMSIjRG4zGa3PBVF8XPQNb0lyTZZNQfgDopLixse8StvFNM7H8oDdrZSeUHL02Sj9YoWpDhsGvl/TB7c/DjLZyNzV3rVzdIRRCmDY7uOnmnOOAWiVX3llFKWDVWCqa9rLxhDBLqQxCxsaq7KUcbNFMWeCe2QcTyh9TpC+VbWlM5VGCqofphxyZeqlQoc3h1lYCGCDAvJwY0YipFJ5cTCb0OZoYNg0p4Cq7yDZ8x0gf+1KyQnRHyjq5GcSsWrZyfsoldb4hcTjSsLmErfS2/MvomVIbGzgH54bNaCYmQtae2R9uKThLZgy3b87PPVzTx1bko07wxlo48nCM7AVQLEkU9fQ972nTz7KLQAli13TaelTqAkb2e783w2XhG4qAhmI2TyqcF2wpVPaKuE4dj+dqaMFCCHCa0CpRC13adu6QnZ4bDsTKerdzl5iI5lnDkCZTCo953YJgMq9VxLx1PJ5205TZ9Wwr40FEyu/XJcXvOVaSMTLh/K57srb5rbzm4Mvnd+c8xp/WcZyMDGgjl34=
